### ISSUE TITLE
Panic when trying to read the CARv1 payload of a CARv2 file

### ISSUE THREAD

**Issue by aarshkshah1992** [ipld/go-car#210]
We saw a weird panic in the Market logs.  So there's a piece of code that reads the CARv1 payload of a CARv2 file and sends it across an http connection. However, it panics because the mmaped `ReaderAt` seems to be trying to read beyond the contents of the file I think. Here's the stacktrace of the panic. The CAR reading code is the first few lines ending at at the `SectionReader` part.  Shouldn't the section reader disallow reading beyond the file size ?

```
unexpected fault address 0x7f6ac3087000
Aug 18 03:17:33 c2 lotus-miner-x[141673]: fatal error: fault
Aug 18 03:17:33 c2 lotus-miner-x[141673]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f6ac3087000 pc=0x5ca5af]
Aug 18 03:17:33 c2 lotus-miner-x[141673]: goroutine 26854198 [running]:
Aug 18 03:17:33 c2 lotus-miner-x[141673]: runtime.throw(0x333a0b1, 0x5)
Aug 18 03:17:33 c2 lotus-miner-x[141673]:         /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc001d15960 sp=0xc001d15930 pc=0x58e972
Aug 18 03:17:33 c2 lotus-miner-x[141673]: runtime.sigpanic()
Aug 18 03:17:33 c2 lotus-miner-x[141673]:         /usr/local/go/src/runtime/signal_unix.go:741 +0x268 fp=0xc001d15998 sp=0xc001d15960 pc=0x5a6468
Aug 18 03:17:33 c2 lotus-miner-x[141673]: runtime.memmove(0xc01b9dc000, 0x7f6ac307f033, 0x8000)
Aug 18 03:17:33 c2 lotus-miner-x[141673]:         /usr/local/go/src/runtime/memmove_amd64.s:345 +0x3ef fp=0xc001d159a0 sp=0xc001d15998 pc=0x5ca5af
Aug 18 03:17:33 c2 lotus-miner-x[141673]: golang.org/x/exp/mmap.(*ReaderAt).ReadAt(0xc02bb82528, 0xc01b9dc000, 0x8000, 0x8000, 0x138033, 0xa34552, 0xc0155153a0, 0xc010057000)
Aug 18 03:17:33 c2 lotus-miner-x[141673]:         /home/shane/go/pkg/mod/golang.org/x/exp@v0.0.0-20210715201039-d37aa40e8013/mmap/mmap_unix.go:73 +0x185 fp=0xc001d15a00 sp=0xc001d159a0 pc=0x1987405
Aug 18 03:17:33 c2 lotus-miner-x[141673]: io.(*SectionReader).Read(0xc02dff1830, 0xc01b9dc000, 0x8000, 0x8000, 0x70c71b, 0xc02cbb66c0, 0xc010057000)
Aug 18 03:17:33 c2 lotus-miner-x[141673]:         /usr/local/go/src/io/io.go:500 +0x7d fp=0xc001d15a50 sp=0xc001d15a00 pc=0x6101bd
Aug 18 03:17:33 c2 lotus-miner-x[141673]: io.(*LimitedReader).Read(0xc02bb82570, 0xc01b9dc000, 0x8000, 0x8000, 0x0, 0x8000, 0xc001d15b40)
Aug 18 03:17:33 c2 lotus-miner-x[141673]:         /usr/local/go/src/io/io.go:473 +0x63 fp=0xc001d15a98 sp=0xc001d15a50 pc=0x6100c3
Aug 18 03:17:33 c2 lotus-miner-x[141673]: io.(*multiReader).Read(0xc02bb825a0, 0xc01b9dc000, 0x8000, 0x8000, 0x8000, 0x2ef6de0, 0xc0414948d8)
Aug 18 03:17:33 c2 lotus-miner-x[141673]:         /usr/local/go/src/io/multi.go:26 +0xb2 fp=0xc001d15b08 sp=0xc001d15a98 pc=0x610b12
Aug 18 03:17:33 c2 lotus-miner-x[141673]: io.(*nopCloser).Read(0xc07eac4530, 0xc01b9dc000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
Aug 18 03:17:33 c2 lotus-miner-x[141673]:         <autogenerated>:1 +0x5a fp=0xc001d15b50 sp=0xc001d15b08 pc=0x61285a
Aug 18 03:17:33 c2 lotus-miner-x[141673]: io.copyBuffer(0x7f73b00b6bf8, 0xc0460b7d40, 0x7f73b00b6bd8, 0xc07eac4530, 0xc01b9dc000, 0x8000, 0x8000, 0xc001d15c38, 0x561d25, 0x2fffa00)
Aug 18 03:17:33 c2 lotus-miner-x[141673]:         /usr/local/go/src/io/io.go:423 +0x12c fp=0xc001d15bd0 sp=0xc001d15b50 pc=0x60fd8c
```

**Comment by willscott** [comment]
The stack trace doesn't really provide enough to say anything here
It's as likely that the destination buffer you're copying into is getting de-allocated part way through the copy because the network connection gets closed. Is that possible?

**Comment by aarshkshah1992** [comment]
@willscott If that was the case, why would the panic be in the `ReadAt` call ?

**Comment by willscott** [comment]
It's happening in the `memmove` / `copy` of memory into the destination buffer that results within the `ReadAt` call

**Comment by aarshkshah1992** [comment]
I see. It is possible for that connection to have been closed, yes. Let me close this issue and get back with more findings. Thank you.
